-- Field encryption platform and work authorization (design A6.3 "Field
-- encryption scheme", B2.4 `work_authorization`, B4.4, B4.6, B6 key-rotation
-- and visa-expiry; FR-VIS-01 to 03, FR-NTF-11).
--
-- 1. eureka.field_key: one row per data key version of a field class. The
--    data key itself is generated by KMS (FIELD_KMS_KEY_ARN, encryption
--    context purpose/class/key id) and stored only wrapped; the API and the
--    worker unwrap it in memory. Local development uses a local provider that
--    the application refuses in production. Rows are added only through
--    authz.field_key_first (API, first use of a class) and
--    authz.field_key_rotate (worker, monthly key-rotation job); never changed
--    or deleted (old versions decrypt rows until rotation reaches them).
-- 2. Ciphertext format (bytea, application-side AES-256-GCM):
--      0x01 | key id (16 bytes) | key version (uint32 BE) | IV (12) | ciphertext | tag (16)
--    The AAD binds the header and the table, column and row id, so a value
--    copied to another row or column does not decrypt. CHECKs below tie the
--    header's key id to the key column.
-- 3. eureka.work_authorization: per person (candidate or employee), number
--    encrypted (class work_auth_number). Read: visa:read covering the owning
--    candidate (HR, Immigration at org scope) and the candidate readable.
--    This is narrower than B4.4's "document:read scope" (open question in
--    docs/HANDOFF.md); the conservative rule is kept until Ravi decides.
--    Writes only through authz.work_auth_create / authz.work_auth_update
--    (visa:update covering the candidate). Rows are never deleted (status
--    revoked instead).
-- 4. Expiry notices: authz.work_auth_expiry_notices (worker) inserts
--    `work_authorization.expiring` outbox rows (ids, dates and thresholds only;
--    no number, no type) once per (record, threshold, expiry date). Delivery
--    and the inbox are built separately (docs/work-authorization-api.md).
-- 5. DOB (OD-04 still open): no read or write path is added. person.dob_enc
--    and dob_bidx only get format CHECKs so that anything written later uses
--    this envelope format and a 32-byte HMAC-SHA256 blind index.
-- Every IF is NULL-safe (see 0012/0015).
SET search_path = eureka, public;

SET ROLE eureka_owner;

-- ---------- 1. data keys ----------
CREATE TABLE eureka.field_key (
  id           uuid PRIMARY KEY,
  field_class  text NOT NULL CHECK (field_class IN ('work_auth_number', 'dob')),
  version      integer NOT NULL CHECK (version >= 1),
  provider     text NOT NULL CHECK (provider IN ('kms', 'local')),
  -- KMS key ARN, or the local provider's key label.
  key_ref      text NOT NULL CHECK (char_length(key_ref) BETWEEN 1 AND 300),
  wrapped_key  bytea NOT NULL CHECK (octet_length(wrapped_key) BETWEEN 16 AND 1024),
  -- The key-rotation run (UTC month) that created it; NULL for a class's first key.
  rotation_key text CHECK (rotation_key ~ '^[0-9]{4}-(0[1-9]|1[0-2])$'),
  created_at   timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT field_key_version_unique UNIQUE (field_class, version),
  CONSTRAINT field_key_rotation_unique UNIQUE (field_class, rotation_key)
);

CREATE FUNCTION eureka.field_key_guard() RETURNS trigger
LANGUAGE plpgsql SET search_path = pg_catalog, pg_temp AS $$
BEGIN
  IF TG_OP IS DISTINCT FROM 'INSERT' OR current_user IS DISTINCT FROM 'authz_definer' THEN
    RAISE EXCEPTION 'field keys are only added, through definer functions' USING ERRCODE = 'insufficient_privilege';
  END IF;
  NEW.created_at := pg_catalog.now();
  RETURN NEW;
END $$;
CREATE TRIGGER field_key_guard BEFORE INSERT OR UPDATE OR DELETE ON eureka.field_key
  FOR EACH ROW EXECUTE FUNCTION eureka.field_key_guard();
CREATE TRIGGER field_key_no_truncate BEFORE TRUNCATE ON eureka.field_key
  FOR EACH STATEMENT EXECUTE FUNCTION eureka.field_key_guard();

ALTER TABLE eureka.field_key ENABLE ROW LEVEL SECURITY; ALTER TABLE eureka.field_key FORCE ROW LEVEL SECURITY;
-- Wrapped keys are useless without KMS (or, locally, the development key).
CREATE POLICY field_key_app_read    ON eureka.field_key FOR SELECT TO eureka_app USING (true);
CREATE POLICY field_key_worker_read ON eureka.field_key FOR SELECT TO eureka_worker USING (true);
CREATE POLICY definer_read          ON eureka.field_key FOR SELECT TO authz_definer USING (true);
CREATE POLICY definer_insert        ON eureka.field_key FOR INSERT TO authz_definer WITH CHECK (true);

-- ---------- 3. work authorization ----------
CREATE TABLE eureka.work_authorization (
  id            uuid PRIMARY KEY,
  person_id     uuid NOT NULL REFERENCES eureka.person(id),
  auth_type     text NOT NULL CHECK (auth_type IN (
                  'h1b', 'h4_ead', 'l1', 'l2_ead', 'f1_opt', 'f1_stem_opt', 'f1_cpt',
                  'gc_ead', 'green_card', 'tn', 'o1', 'other')),
  number_enc    bytea,
  number_key_id uuid REFERENCES eureka.field_key(id),
  valid_from    date,
  valid_to      date,
  status        text NOT NULL CHECK (status IN ('pending', 'valid', 'revoked')),
  row_version   integer NOT NULL DEFAULT 1 CHECK (row_version >= 1),
  created_by    uuid NOT NULL REFERENCES eureka.app_user(id),
  created_at    timestamptz NOT NULL DEFAULT now(),
  updated_by    uuid NOT NULL REFERENCES eureka.app_user(id),
  updated_at    timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT work_authorization_number_key CHECK ((number_enc IS NULL) = (number_key_id IS NULL)),
  CONSTRAINT work_authorization_number_format CHECK (
    number_enc IS NULL OR (
      pg_catalog.get_byte(number_enc, 0) = 1
      AND octet_length(number_enc) BETWEEN 50 AND 200
      AND substring(number_enc FROM 2 FOR 16) = pg_catalog.uuid_send(number_key_id))),
  CONSTRAINT work_authorization_dates CHECK (valid_from IS NULL OR valid_to IS NULL OR valid_to >= valid_from),
  CONSTRAINT work_authorization_date_range CHECK (
    (valid_from IS NULL OR valid_from BETWEEN DATE '1950-01-01' AND DATE '2200-01-01')
    AND (valid_to IS NULL OR valid_to BETWEEN DATE '1950-01-01' AND DATE '2200-01-01'))
);
CREATE INDEX work_authorization_person ON eureka.work_authorization (person_id, valid_to DESC);
CREATE INDEX work_authorization_expiring ON eureka.work_authorization (valid_to) WHERE status = 'valid';
CREATE INDEX work_authorization_number_key ON eureka.work_authorization (number_key_id) WHERE number_key_id IS NOT NULL;

-- Rules 4 and 6: only definer functions write; the server sets every managed
-- column. With a user (API functions) every update bumps row_version and the
-- updated_* columns; without one (the worker's rotation) only the ciphertext
-- and its key may change.
CREATE FUNCTION eureka.work_authorization_guard() RETURNS trigger
LANGUAGE plpgsql SET search_path = pg_catalog, pg_temp AS $$
DECLARE actor uuid := authz.current_user_id();
BEGIN
  IF current_user IS DISTINCT FROM 'authz_definer' THEN
    RAISE EXCEPTION 'work authorization rows are written only by definer functions' USING ERRCODE = 'insufficient_privilege';
  END IF;
  IF TG_OP = 'DELETE' THEN
    RAISE EXCEPTION 'work authorization rows are not deleted' USING ERRCODE = 'insufficient_privilege';
  END IF;
  IF TG_OP = 'INSERT' THEN
    IF actor IS NULL THEN
      RAISE EXCEPTION 'not_permitted' USING ERRCODE = 'insufficient_privilege';
    END IF;
    NEW.row_version := 1;
    NEW.created_by := actor;
    NEW.updated_by := actor;
    NEW.created_at := pg_catalog.now();
    NEW.updated_at := pg_catalog.now();
    RETURN NEW;
  END IF;
  IF (NEW.id, NEW.person_id, NEW.created_by, NEW.created_at) IS DISTINCT FROM (OLD.id, OLD.person_id, OLD.created_by, OLD.created_at) THEN
    RAISE EXCEPTION 'column is immutable' USING ERRCODE = 'insufficient_privilege';
  END IF;
  IF actor IS NULL THEN
    IF (NEW.auth_type, NEW.valid_from, NEW.valid_to, NEW.status, NEW.row_version, NEW.updated_by, NEW.updated_at)
       IS DISTINCT FROM (OLD.auth_type, OLD.valid_from, OLD.valid_to, OLD.status, OLD.row_version, OLD.updated_by, OLD.updated_at)
       OR NEW.number_enc IS NULL OR OLD.number_enc IS NULL THEN
      RAISE EXCEPTION 'key rotation changes only the ciphertext' USING ERRCODE = 'insufficient_privilege';
    END IF;
    RETURN NEW;
  END IF;
  NEW.row_version := OLD.row_version + 1;
  NEW.updated_by := actor;
  NEW.updated_at := pg_catalog.now();
  RETURN NEW;
END $$;
CREATE TRIGGER work_authorization_guard BEFORE INSERT OR UPDATE OR DELETE ON eureka.work_authorization
  FOR EACH ROW EXECUTE FUNCTION eureka.work_authorization_guard();

CREATE FUNCTION eureka.work_authorization_no_truncate() RETURNS trigger
LANGUAGE plpgsql SET search_path = pg_catalog, pg_temp AS $$
BEGIN
  RAISE EXCEPTION '% is not truncated', TG_TABLE_NAME USING ERRCODE = 'insufficient_privilege';
END $$;
CREATE TRIGGER work_authorization_no_truncate BEFORE TRUNCATE ON eureka.work_authorization
  FOR EACH STATEMENT EXECUTE FUNCTION eureka.work_authorization_no_truncate();

ALTER TABLE eureka.work_authorization ENABLE ROW LEVEL SECURITY; ALTER TABLE eureka.work_authorization FORCE ROW LEVEL SECURITY;

-- Rule 3: scope arrays are InitPlans; the EXISTS is an index probe on
-- candidate.person_id (unique) that also runs under the caller's candidate
-- policy, so the candidate must be readable too.
CREATE POLICY work_authorization_read ON eureka.work_authorization FOR SELECT TO eureka_app USING (
  EXISTS (SELECT 1 FROM eureka.candidate c WHERE c.person_id = work_authorization.person_id AND (
    (SELECT authz.has_org('visa:read'))
    OR c.recruiter_id = ANY ((SELECT authz.recruiter_ids('visa:read'))::uuid[])
    OR c.team_id      = ANY ((SELECT authz.team_ids('visa:read'))::uuid[])
    OR c.location_id  = ANY ((SELECT authz.location_ids('visa:read'))::uuid[])))
);
CREATE POLICY definer_read   ON eureka.work_authorization FOR SELECT TO authz_definer USING (true);
CREATE POLICY definer_insert ON eureka.work_authorization FOR INSERT TO authz_definer WITH CHECK (true);
CREATE POLICY definer_update ON eureka.work_authorization FOR UPDATE TO authz_definer USING (true) WITH CHECK (true);

-- ---------- 4. expiry notice ledger (one notice per record, threshold, expiry date) ----------
CREATE TABLE eureka.work_authorization_notice (
  work_authorization_id uuid NOT NULL REFERENCES eureka.work_authorization(id),
  threshold_days        integer NOT NULL CHECK (threshold_days BETWEEN 1 AND 365),
  valid_to              date NOT NULL,
  outbox_event_id       uuid NOT NULL,
  created_at            timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (work_authorization_id, valid_to, threshold_days)
);

CREATE FUNCTION eureka.work_authorization_notice_guard() RETURNS trigger
LANGUAGE plpgsql SET search_path = pg_catalog, pg_temp AS $$
BEGIN
  IF TG_OP IS DISTINCT FROM 'INSERT' OR current_user IS DISTINCT FROM 'authz_definer' THEN
    RAISE EXCEPTION 'expiry notices are only added, by the expiry job' USING ERRCODE = 'insufficient_privilege';
  END IF;
  NEW.created_at := pg_catalog.now();
  RETURN NEW;
END $$;
CREATE TRIGGER work_authorization_notice_guard BEFORE INSERT OR UPDATE OR DELETE ON eureka.work_authorization_notice
  FOR EACH ROW EXECUTE FUNCTION eureka.work_authorization_notice_guard();
CREATE TRIGGER work_authorization_notice_no_truncate BEFORE TRUNCATE ON eureka.work_authorization_notice
  FOR EACH STATEMENT EXECUTE FUNCTION eureka.work_authorization_no_truncate();

ALTER TABLE eureka.work_authorization_notice ENABLE ROW LEVEL SECURITY; ALTER TABLE eureka.work_authorization_notice FORCE ROW LEVEL SECURITY;
CREATE POLICY definer_read   ON eureka.work_authorization_notice FOR SELECT TO authz_definer USING (true);
CREATE POLICY definer_insert ON eureka.work_authorization_notice FOR INSERT TO authz_definer WITH CHECK (true);

-- ---------- 5. DOB format (no read or write path; OD-04) ----------
ALTER TABLE eureka.person
  ADD CONSTRAINT person_dob_enc_format CHECK (
    dob_enc IS NULL OR (pg_catalog.get_byte(dob_enc, 0) = 1 AND octet_length(dob_enc) BETWEEN 50 AND 200)),
  ADD CONSTRAINT person_dob_bidx_format CHECK (dob_bidx IS NULL OR octet_length(dob_bidx) = 32),
  ADD CONSTRAINT person_dob_bidx_needs_value CHECK (dob_bidx IS NULL OR dob_enc IS NOT NULL);

RESET ROLE;

REVOKE ALL ON eureka.field_key, eureka.work_authorization, eureka.work_authorization_notice FROM PUBLIC;
REVOKE ALL ON FUNCTION eureka.field_key_guard() FROM PUBLIC;
REVOKE ALL ON FUNCTION eureka.work_authorization_guard() FROM PUBLIC;
REVOKE ALL ON FUNCTION eureka.work_authorization_notice_guard() FROM PUBLIC;
REVOKE ALL ON FUNCTION eureka.work_authorization_no_truncate() FROM PUBLIC;

GRANT SELECT ON eureka.field_key TO eureka_app, eureka_worker;
GRANT SELECT, INSERT ON eureka.field_key TO authz_definer;
-- The app reads the ciphertext (reveal decrypts it in the API, audited).
GRANT SELECT ON eureka.work_authorization TO eureka_app;
GRANT SELECT, INSERT ON eureka.work_authorization TO authz_definer;
GRANT UPDATE (auth_type, number_enc, number_key_id, valid_from, valid_to, status, row_version, updated_by, updated_at)
  ON eureka.work_authorization TO authz_definer;
GRANT SELECT, INSERT ON eureka.work_authorization_notice TO authz_definer;

-- ---------- functions ----------
SET ROLE authz_definer;

-- API: the first data key of a class (none exists yet). When one exists, it
-- is returned and nothing is added (the caller discards the key it generated).
CREATE FUNCTION authz.field_key_first(p_id uuid, p_class text, p_provider text, p_key_ref text, p_wrapped bytea)
RETURNS TABLE (id uuid, version integer)
LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog, pg_temp AS $$
BEGIN
  IF authz.current_user_id() IS NULL THEN
    RAISE EXCEPTION 'not_permitted' USING ERRCODE = 'insufficient_privilege';
  END IF;
  IF p_id IS NULL OR p_class IS NULL THEN
    RAISE EXCEPTION 'invalid_key' USING ERRCODE = 'check_violation';
  END IF;
  PERFORM pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended('field_key:' || p_class, 0));
  IF NOT EXISTS (SELECT 1 FROM eureka.field_key k WHERE k.field_class = p_class) THEN
    INSERT INTO eureka.field_key (id, field_class, version, provider, key_ref, wrapped_key, rotation_key)
    VALUES (p_id, p_class, 1, p_provider, p_key_ref, p_wrapped, NULL);
  END IF;
  RETURN QUERY SELECT k.id, k.version FROM eureka.field_key k
    WHERE k.field_class = p_class ORDER BY k.version DESC LIMIT 1;
END $$;

-- Worker: the key of one rotation run (UTC month). Idempotent per run: a
-- retried run gets the key the first attempt added.
CREATE FUNCTION authz.field_key_rotate(p_id uuid, p_class text, p_provider text, p_key_ref text, p_wrapped bytea, p_rotation_key text)
RETURNS TABLE (id uuid, version integer)
LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog, pg_temp AS $$
BEGIN
  IF p_id IS NULL OR p_class IS NULL OR p_rotation_key IS NULL
     OR NOT coalesce(p_rotation_key ~ '^[0-9]{4}-(0[1-9]|1[0-2])$', false) THEN
    RAISE EXCEPTION 'invalid_key' USING ERRCODE = 'check_violation';
  END IF;
  IF p_rotation_key > pg_catalog.to_char(pg_catalog.now() AT TIME ZONE 'UTC', 'YYYY-MM') THEN
    RAISE EXCEPTION 'rotation key is in the future' USING ERRCODE = 'check_violation';
  END IF;
  PERFORM pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended('field_key:' || p_class, 0));
  IF NOT EXISTS (SELECT 1 FROM eureka.field_key k WHERE k.field_class = p_class AND k.rotation_key = p_rotation_key) THEN
    INSERT INTO eureka.field_key (id, field_class, version, provider, key_ref, wrapped_key, rotation_key)
    VALUES (p_id, p_class,
            (SELECT coalesce(pg_catalog.max(k.version), 0) + 1 FROM eureka.field_key k WHERE k.field_class = p_class),
            p_provider, p_key_ref, p_wrapped, p_rotation_key);
  END IF;
  RETURN QUERY SELECT k.id, k.version FROM eureka.field_key k
    WHERE k.field_class = p_class AND k.rotation_key = p_rotation_key;
END $$;

-- The newest key of a class (rotation target).
CREATE FUNCTION authz.field_key_newest(p_class text) RETURNS uuid
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = pg_catalog, pg_temp AS $$
  SELECT k.id FROM eureka.field_key k WHERE k.field_class = p_class ORDER BY k.version DESC LIMIT 1
$$;

-- Worker: rows of a class not yet under the newest key (ciphertext and ids
-- only), in id order after p_after (one pass per run; a row an API write
-- changed meanwhile is picked up by the next run).
CREATE FUNCTION authz.field_rotation_batch(p_class text, p_key uuid, p_after uuid, p_limit integer)
RETURNS TABLE (row_id uuid, enc bytea, key_id uuid)
LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path = pg_catalog, pg_temp AS $$
BEGIN
  IF p_class IS DISTINCT FROM 'work_auth_number' THEN
    RAISE EXCEPTION 'unsupported field class' USING ERRCODE = 'check_violation';
  END IF;
  IF p_key IS NULL OR p_key IS DISTINCT FROM authz.field_key_newest(p_class) THEN
    RAISE EXCEPTION 'not_current_key' USING ERRCODE = 'check_violation';
  END IF;
  RETURN QUERY
  SELECT w.id, w.number_enc, w.number_key_id FROM eureka.work_authorization w
   WHERE w.number_enc IS NOT NULL AND w.number_key_id IS DISTINCT FROM p_key
     AND (p_after IS NULL OR w.id > p_after)
   ORDER BY w.id
   LIMIT LEAST(GREATEST(coalesce(p_limit, 0), 0), 500);
END $$;

-- Worker: swaps one row's ciphertext to the newest key, only if the row still
-- holds the ciphertext the worker decrypted (an API write in between wins)
-- and only forward (a newer key version). Returns false when nothing changed.
CREATE FUNCTION authz.field_rotation_apply(p_class text, p_row uuid, p_old_enc bytea, p_new_enc bytea, p_new_key uuid)
RETURNS boolean
LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog, pg_temp AS $$
DECLARE new_version integer; old_version integer;
BEGIN
  IF p_class IS DISTINCT FROM 'work_auth_number' THEN
    RAISE EXCEPTION 'unsupported field class' USING ERRCODE = 'check_violation';
  END IF;
  IF p_row IS NULL OR p_old_enc IS NULL OR p_new_enc IS NULL
     OR p_new_key IS NULL OR p_new_key IS DISTINCT FROM authz.field_key_newest(p_class) THEN
    RAISE EXCEPTION 'not_current_key' USING ERRCODE = 'check_violation';
  END IF;
  SELECT k.version INTO new_version FROM eureka.field_key k WHERE k.id = p_new_key;
  SELECT k.version INTO old_version FROM eureka.field_key k
    JOIN eureka.work_authorization w ON w.number_key_id = k.id WHERE w.id = p_row;
  IF old_version IS NULL OR NOT coalesce(new_version > old_version, false) THEN
    RETURN false;
  END IF;
  UPDATE eureka.work_authorization w SET number_enc = p_new_enc, number_key_id = p_new_key
   WHERE w.id = p_row AND w.number_enc = p_old_enc;
  RETURN FOUND;
END $$;

-- A data key of the right class for a new ciphertext (NULL number: no key).
CREATE FUNCTION authz.work_auth_check_key(p_enc bytea, p_key uuid) RETURNS void
LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path = pg_catalog, pg_temp AS $$
BEGIN
  IF (p_enc IS NULL) IS DISTINCT FROM (p_key IS NULL) THEN
    RAISE EXCEPTION 'invalid_number' USING ERRCODE = 'check_violation';
  END IF;
  IF p_key IS NOT NULL AND NOT EXISTS (
       SELECT 1 FROM eureka.field_key k WHERE k.id = p_key AND k.field_class = 'work_auth_number') THEN
    RAISE EXCEPTION 'invalid_number' USING ERRCODE = 'check_violation';
  END IF;
END $$;

-- API: a new record for a candidate's person. 404-equivalent when the
-- candidate is not readable or visa:read does not cover it; 403 when
-- visa:update does not cover it. The id comes from the API because the
-- ciphertext is bound to it.
CREATE FUNCTION authz.work_auth_create(
  p_id uuid, p_candidate uuid, p_type text, p_number_enc bytea, p_number_key uuid,
  p_valid_from date, p_valid_to date, p_status text)
RETURNS integer
LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog, pg_temp AS $$
DECLARE v_person uuid;
BEGIN
  IF authz.current_user_id() IS NULL THEN
    RAISE EXCEPTION 'not_permitted' USING ERRCODE = 'insufficient_privilege';
  END IF;
  IF p_candidate IS NULL
     OR NOT coalesce(authz.candidate_visible(p_candidate, 'candidate:read'), false)
     OR NOT coalesce(authz.candidate_owned(p_candidate, 'visa:read'), false) THEN
    RAISE EXCEPTION 'not_found' USING ERRCODE = 'no_data_found';
  END IF;
  IF NOT coalesce(authz.candidate_owned(p_candidate, 'visa:update'), false) THEN
    RAISE EXCEPTION 'not_permitted' USING ERRCODE = 'insufficient_privilege';
  END IF;
  IF p_id IS NULL OR p_type IS NULL OR p_status IS NULL THEN
    RAISE EXCEPTION 'invalid_record' USING ERRCODE = 'check_violation';
  END IF;
  PERFORM authz.work_auth_check_key(p_number_enc, p_number_key);
  SELECT c.person_id INTO v_person FROM eureka.candidate c WHERE c.id = p_candidate;
  INSERT INTO eureka.work_authorization (id, person_id, auth_type, number_enc, number_key_id, valid_from, valid_to, status,
                                         created_by, updated_by)
  VALUES (p_id, v_person, p_type, p_number_enc, p_number_key, p_valid_from, p_valid_to, p_status,
          authz.current_user_id(), authz.current_user_id());
  RETURN 1;
END $$;

-- API: replaces the editable fields of one record (the API merges a partial
-- update first). p_set_number false keeps the stored ciphertext. Optimistic
-- concurrency on row_version ('stale'). Returns the new row_version.
CREATE FUNCTION authz.work_auth_update(
  p_id uuid, p_candidate uuid, p_row_version integer, p_type text, p_set_number boolean, p_number_enc bytea, p_number_key uuid,
  p_valid_from date, p_valid_to date, p_status text)
RETURNS integer
LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog, pg_temp AS $$
DECLARE w eureka.work_authorization%ROWTYPE; out_version integer;
BEGIN
  IF authz.current_user_id() IS NULL THEN
    RAISE EXCEPTION 'not_permitted' USING ERRCODE = 'insufficient_privilege';
  END IF;
  SELECT x.* INTO w FROM eureka.work_authorization x
    JOIN eureka.candidate c ON c.person_id = x.person_id
   WHERE x.id = p_id AND c.id = p_candidate
   FOR UPDATE OF x;
  IF NOT FOUND
     OR NOT coalesce(authz.candidate_visible(p_candidate, 'candidate:read'), false)
     OR NOT coalesce(authz.candidate_owned(p_candidate, 'visa:read'), false) THEN
    RAISE EXCEPTION 'not_found' USING ERRCODE = 'no_data_found';
  END IF;
  IF NOT coalesce(authz.candidate_owned(p_candidate, 'visa:update'), false) THEN
    RAISE EXCEPTION 'not_permitted' USING ERRCODE = 'insufficient_privilege';
  END IF;
  IF p_row_version IS NULL OR p_row_version IS DISTINCT FROM w.row_version THEN
    RAISE EXCEPTION 'stale' USING ERRCODE = 'check_violation';
  END IF;
  IF p_type IS NULL OR p_status IS NULL OR p_set_number IS NULL THEN
    RAISE EXCEPTION 'invalid_record' USING ERRCODE = 'check_violation';
  END IF;
  IF p_set_number THEN
    PERFORM authz.work_auth_check_key(p_number_enc, p_number_key);
    UPDATE eureka.work_authorization x
       SET auth_type = p_type, number_enc = p_number_enc, number_key_id = p_number_key,
           valid_from = p_valid_from, valid_to = p_valid_to, status = p_status
     WHERE x.id = p_id RETURNING x.row_version INTO out_version;
  ELSE
    UPDATE eureka.work_authorization x
       SET auth_type = p_type, valid_from = p_valid_from, valid_to = p_valid_to, status = p_status
     WHERE x.id = p_id RETURNING x.row_version INTO out_version;
  END IF;
  RETURN out_version;
END $$;

-- Worker: expiry notices (FR-VIS-03, FR-NTF-11). For each valid record whose
-- valid_to is today or later and within the largest threshold, the smallest
-- threshold already reached is noticed once per expiry date: a record entered
-- 20 days before expiry gets the 30-day notice only; a missed day is caught up
-- on the next run. "Today" is the America/New_York calendar day of the
-- database clock (the worker cannot move it). Returns the number of events.
CREATE FUNCTION authz.work_auth_expiry_notices(p_thresholds integer[]) RETURNS integer
LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog, pg_temp AS $$
DECLARE
  today date := (pg_catalog.now() AT TIME ZONE 'America/New_York')::date;
  max_days integer;
  r record;
  t integer;
  ev uuid;
  n integer := 0;
BEGIN
  IF p_thresholds IS NULL OR coalesce(pg_catalog.cardinality(p_thresholds), 0) NOT BETWEEN 1 AND 10
     OR EXISTS (SELECT 1 FROM pg_catalog.unnest(p_thresholds) x WHERE x IS NULL OR x NOT BETWEEN 1 AND 365) THEN
    RAISE EXCEPTION 'invalid thresholds' USING ERRCODE = 'check_violation';
  END IF;
  PERFORM pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended('work_auth_expiry_notices', 0));
  SELECT pg_catalog.max(x) INTO max_days FROM pg_catalog.unnest(p_thresholds) x;
  FOR r IN
    SELECT w.id, w.person_id, w.valid_to, c.id AS candidate_id, (w.valid_to - today) AS days_left
      FROM eureka.work_authorization w
      JOIN eureka.candidate c ON c.person_id = w.person_id
     WHERE w.status = 'valid' AND w.valid_to IS NOT NULL
       AND w.valid_to >= today AND w.valid_to <= today + max_days
     ORDER BY w.valid_to, w.id
  LOOP
    SELECT pg_catalog.min(x) INTO t FROM pg_catalog.unnest(p_thresholds) x WHERE x >= r.days_left;
    IF t IS NULL OR EXISTS (
         SELECT 1 FROM eureka.work_authorization_notice wn
          WHERE wn.work_authorization_id = r.id AND wn.valid_to = r.valid_to AND wn.threshold_days <= t) THEN
      CONTINUE;
    END IF;
    ev := pg_catalog.gen_random_uuid();
    INSERT INTO eureka.work_authorization_notice (work_authorization_id, threshold_days, valid_to, outbox_event_id)
    VALUES (r.id, t, r.valid_to, ev);
    -- Rule 5: ids, dates and numbers of days only (no work authorization number or type).
    INSERT INTO eureka.outbox_event (id, type, aggregate_type, aggregate_id, payload)
    VALUES (ev, 'work_authorization.expiring', 'work_authorization', r.id, pg_catalog.jsonb_build_object(
      'candidate_id', r.candidate_id,
      'person_id', r.person_id,
      'expires_on', r.valid_to,
      'threshold_days', t,
      'days_left', r.days_left,
      'notify', pg_catalog.jsonb_build_array('hr', 'immigration')));
    n := n + 1;
  END LOOP;
  RETURN n;
END $$;

RESET ROLE;

REVOKE ALL ON FUNCTION authz.field_key_first(uuid, text, text, text, bytea) FROM PUBLIC;
REVOKE ALL ON FUNCTION authz.field_key_rotate(uuid, text, text, text, bytea, text) FROM PUBLIC;
REVOKE ALL ON FUNCTION authz.field_key_newest(text) FROM PUBLIC;
REVOKE ALL ON FUNCTION authz.field_rotation_batch(text, uuid, uuid, integer) FROM PUBLIC;
REVOKE ALL ON FUNCTION authz.field_rotation_apply(text, uuid, bytea, bytea, uuid) FROM PUBLIC;
REVOKE ALL ON FUNCTION authz.work_auth_check_key(bytea, uuid) FROM PUBLIC;
REVOKE ALL ON FUNCTION authz.work_auth_create(uuid, uuid, text, bytea, uuid, date, date, text) FROM PUBLIC;
REVOKE ALL ON FUNCTION authz.work_auth_update(uuid, uuid, integer, text, boolean, bytea, uuid, date, date, text) FROM PUBLIC;
REVOKE ALL ON FUNCTION authz.work_auth_expiry_notices(integer[]) FROM PUBLIC;

GRANT EXECUTE ON FUNCTION authz.field_key_first(uuid, text, text, text, bytea) TO eureka_app;
GRANT EXECUTE ON FUNCTION authz.work_auth_create(uuid, uuid, text, bytea, uuid, date, date, text) TO eureka_app;
GRANT EXECUTE ON FUNCTION authz.work_auth_update(uuid, uuid, integer, text, boolean, bytea, uuid, date, date, text) TO eureka_app;
GRANT EXECUTE ON FUNCTION authz.field_key_rotate(uuid, text, text, text, bytea, text) TO eureka_worker;
GRANT EXECUTE ON FUNCTION authz.field_key_newest(text) TO eureka_worker;
GRANT EXECUTE ON FUNCTION authz.field_rotation_batch(text, uuid, uuid, integer) TO eureka_worker;
GRANT EXECUTE ON FUNCTION authz.field_rotation_apply(text, uuid, bytea, bytea, uuid) TO eureka_worker;
GRANT EXECUTE ON FUNCTION authz.work_auth_expiry_notices(integer[]) TO eureka_worker;
-- work_auth_check_key and field_key_newest are called from the definer functions (owner authz_definer).
