import { FieldCryptoError, sealWith, type FieldCipher, type FieldClass } from "../../platform/crypto/field-crypto.js";
import type { JobDefinition } from "../runner.js";
import { KEY_ROTATION_SCHEDULE, dueMonthlyKeys } from "../schedule.js";

/**
 * key-rotation (design A6.3, B6; migration 0042). Monthly, run key = UTC month
 * ("YYYY-MM"). For each rotated field class:
 *  1. authz.field_key_rotate adds the month's data key version (generated by
 *     the key provider), or returns it when an earlier attempt of the same run
 *     added it: one key per class and month however often the run is retried.
 *  2. Rows not yet under that key are read in id order, in batches
 *     (authz.field_rotation_batch: ciphertext and ids only), decrypted with
 *     their old key and encrypted with the new one, bound to the same row.
 *  3. authz.field_rotation_apply swaps the ciphertext only if the row still
 *     holds what was read (a concurrent API write wins; the next run covers
 *     that row) and only forward to a newer key version.
 * Idempotent: a re-run of the same month finds nothing left to do. The runner's
 * lease keeps two workers from running the same month at once; the job checks
 * its abort signal between rows and touches the heartbeat between batches.
 *
 * Plaintext stays in this function's locals: nothing is logged or written to
 * job_run except counts and key versions. A row that does not decrypt
 * (corrupted, or bound to another row) is counted, logged by id with an alert,
 * and left as it is.
 */
export const KEY_ROTATION_JOB = "key-rotation";

/** Classes the job rotates. dob joins once DOB is written (OD-04). */
export const ROTATED_CLASSES: readonly FieldClass[] = ["work_auth_number"];

export interface KeyRotationOptions { batchSize: number; classes?: readonly FieldClass[] }

interface Pending extends Record<string, unknown> { row_id: string; enc: Buffer; key_id: string }

export function keyRotationJob(cipher: FieldCipher, o: KeyRotationOptions): JobDefinition {
  return {
    name: KEY_ROTATION_JOB,
    dueKeys: (now) => dueMonthlyKeys(now, KEY_ROTATION_SCHEDULE),
    async run(runKey, { pool, log, signal, heartbeat }) {
      const detail: Record<string, unknown> = {};
      for (const cls of o.classes ?? ROTATED_CLASSES) {
        const key = await cipher.rotationKey(pool, cls, runKey);
        let after: string | null = null;
        let reencrypted = 0, skipped = 0, failed = 0;
        for (;;) {
          signal.throwIfAborted();
          const batch: Pending[] = (await pool.query<Pending>(
            `SELECT row_id, enc, key_id FROM authz.field_rotation_batch($1, $2, $3, $4)`, [cls, key.id, after, o.batchSize])).rows;
          if (batch.length === 0) break;
          for (const r of batch) {
            signal.throwIfAborted();
            after = r.row_id;
            const ref = { cls, rowId: r.row_id };
            let next: Buffer;
            try {
              next = sealWith(key, ref, await cipher.decrypt(pool, ref, r.enc));
            } catch (err) {
              if (!(err instanceof FieldCryptoError)) throw err;
              failed++;
              log.error("key rotation: a value does not decrypt; left unchanged", { job: KEY_ROTATION_JOB, cls, rowId: r.row_id, alert: true });
              continue;
            }
            const ok = (await pool.query<{ ok: boolean }>(
              `SELECT authz.field_rotation_apply($1, $2, $3, $4, $5) AS ok`, [cls, r.row_id, r.enc, next, key.id])).rows[0]!.ok;
            if (ok) reencrypted++; else skipped++;
          }
          heartbeat();
        }
        detail[cls] = { keyVersion: key.version, reencrypted, skipped, failed };
      }
      return detail;
    },
  };
}
