import { createCipheriv, createDecipheriv, randomBytes, randomUUID } from "node:crypto";
import { FieldCryptoError } from "./errors.js";
import { dataKeyContext, type KeyProvider } from "./key-provider.js";

export { FieldCryptoError };

/**
 * Application-side field encryption (design A6.3; migration 0042).
 *
 * Envelope encryption: each field class has data key versions in
 * eureka.field_key, generated by the key provider (KMS in AWS) and stored only
 * wrapped. A value is encrypted with AES-256-GCM under the newest version:
 *
 *   0x01 | key id (16) | key version (uint32 BE) | IV (12) | ciphertext | tag (16)
 *
 * The AAD is the header plus the table, column and row id ("encryption
 * context"), so a ciphertext moved to another row, column or table, or with a
 * changed header, fails authentication. Unwrapped data keys are cached in
 * memory for up to 24 hours (design A6.3).
 *
 * Plaintext never leaves the calling function: nothing here logs, and errors
 * carry no values. Callers must not put plaintext in audit_event or
 * outbox_event (HANDOFF rule 5).
 */

export const FIELD_CLASSES = {
  /** work_authorization.number_enc */
  work_auth_number: { table: "work_authorization", column: "number" },
  /** person.dob_enc: format and helper only; no read or write path until OD-04 is decided. */
  dob: { table: "person", column: "dob" },
} as const;
export type FieldClass = keyof typeof FIELD_CLASSES;

/** The row a ciphertext belongs to. */
export interface FieldRef { cls: FieldClass; rowId: string }

/** Minimal query interface (a pg Pool or PoolClient). */
export interface Queryable {
  query<R extends Record<string, unknown> = Record<string, unknown>>(sql: string, params?: unknown[]): Promise<{ rows: R[] }>;
}

export interface DataKey { id: string; version: number; cls: FieldClass; key: Buffer }

export const FORMAT_V1 = 1;
const HEADER_LEN = 1 + 16 + 4;
const IV_LEN = 12;
const TAG_LEN = 16;
export const MIN_CIPHERTEXT_LEN = HEADER_LEN + IV_LEN + 1 + TAG_LEN;
export const KEY_CACHE_MS = 24 * 3600_000;
/** Unwrapped data keys kept in memory at most (oldest evicted and zeroed first). */
export const KEY_CACHE_MAX = 64;
const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

const uuidBytes = (id: string) => Buffer.from(id.replace(/-/g, ""), "hex");
const uuidOf = (b: Buffer) => {
  const h = b.toString("hex");
  return `${h.slice(0, 8)}-${h.slice(8, 12)}-${h.slice(12, 16)}-${h.slice(16, 20)}-${h.slice(20)}`;
};

function header(keyId: string, version: number): Buffer {
  const h = Buffer.alloc(HEADER_LEN);
  h.writeUInt8(FORMAT_V1, 0);
  uuidBytes(keyId).copy(h, 1);
  h.writeUInt32BE(version, 17);
  return h;
}

function aad(head: Buffer, ref: FieldRef): Buffer {
  const { table, column } = FIELD_CLASSES[ref.cls];
  if (!UUID.test(ref.rowId)) throw new FieldCryptoError("row id must be a uuid");
  return Buffer.concat([head, Buffer.from(`\0eureka-field:v1\0${table}\0${column}\0${ref.rowId.toLowerCase()}`, "utf8")]);
}

/** Key id and version from a ciphertext header (no decryption). */
export function parseHeader(enc: Buffer): { keyId: string; version: number } {
  if (enc.length < MIN_CIPHERTEXT_LEN || enc.readUInt8(0) !== FORMAT_V1) throw new FieldCryptoError("unsupported ciphertext");
  return { keyId: uuidOf(enc.subarray(1, 17)), version: enc.readUInt32BE(17) };
}

/** AES-256-GCM under one data key, bound to `ref`. */
export function sealWith(key: DataKey, ref: FieldRef, plaintext: string): Buffer {
  if (key.cls !== ref.cls) throw new FieldCryptoError("data key is for another field class");
  const head = header(key.id, key.version);
  const iv = randomBytes(IV_LEN);
  const c = createCipheriv("aes-256-gcm", key.key, iv);
  c.setAAD(aad(head, ref));
  const ct = Buffer.concat([c.update(Buffer.from(plaintext, "utf8")), c.final()]);
  return Buffer.concat([head, iv, ct, c.getAuthTag()]);
}

/** Reverses sealWith; throws FieldCryptoError on any mismatch (key, row, column, tampering). */
export function openWith(key: DataKey, ref: FieldRef, enc: Buffer): string {
  const { keyId, version } = parseHeader(enc);
  if (keyId !== key.id || version !== key.version || key.cls !== ref.cls) throw new FieldCryptoError("ciphertext is not under this data key");
  const head = enc.subarray(0, HEADER_LEN);
  try {
    const d = createDecipheriv("aes-256-gcm", key.key, enc.subarray(HEADER_LEN, HEADER_LEN + IV_LEN));
    d.setAAD(aad(head, ref));
    d.setAuthTag(enc.subarray(enc.length - TAG_LEN));
    return Buffer.concat([d.update(enc.subarray(HEADER_LEN + IV_LEN, enc.length - TAG_LEN)), d.final()]).toString("utf8");
  } catch {
    throw new FieldCryptoError("ciphertext failed authentication");
  }
}

interface KeyRow extends Record<string, unknown> {
  id: string; field_class: FieldClass; version: number; provider: string; key_ref: string; wrapped_key: Buffer;
}

/**
 * Data key management and encryption for the API and the worker. Keys are
 * read from eureka.field_key with the caller's connection (the API's request
 * transaction, the worker's pool).
 *
 * Key material (review finding 6): the cache owns its buffers and never hands
 * them out; callers get a copy (`DataKey`) that they zero with `release` when
 * done. Cache entries expire after 24 hours, at most KEY_CACHE_MAX are kept,
 * and an evicted entry is zeroed.
 */
export class FieldCipher {
  private readonly cache = new Map<string, { key: DataKey; until: number }>();

  constructor(
    readonly provider: KeyProvider,
    private readonly opts: { cacheMs?: number; now?: () => number; maxKeys?: number } = {},
  ) {}

  private now() { return this.opts.now?.() ?? Date.now(); }

  /** A copy of a cached key for one use. */
  private lend(key: DataKey): DataKey {
    return { ...key, key: Buffer.from(key.key) };
  }

  /** Zeroes a key obtained from this cipher (rotationKey, newestKey). */
  release(key: DataKey | null | undefined): void {
    key?.key.fill(0);
  }

  private cached(id: string): DataKey | null {
    const hit = this.cache.get(id);
    if (!hit) return null;
    if (hit.until > this.now()) return hit.key;
    hit.key.key.fill(0);
    this.cache.delete(id);
    return null;
  }

  private remember(key: DataKey) {
    const old = this.cache.get(key.id);
    if (old && old.key.key !== key.key) old.key.key.fill(0);
    this.cache.delete(key.id);
    this.cache.set(key.id, { key, until: this.now() + (this.opts.cacheMs ?? KEY_CACHE_MS) });
    const max = this.opts.maxKeys ?? KEY_CACHE_MAX;
    while (this.cache.size > max) {
      const [oldest, entry] = this.cache.entries().next().value as [string, { key: DataKey }];
      entry.key.key.fill(0);
      this.cache.delete(oldest);
    }
  }

  /** Number of cached keys (tests). */
  get cacheSize() { return this.cache.size; }

  /** Drops and zeroes every cached data key. */
  clearCache() {
    for (const { key } of this.cache.values()) key.key.fill(0);
    this.cache.clear();
  }

  /** The cached key of `row`, unwrapping it first if needed; returns a copy. */
  private async unwrap(row: KeyRow): Promise<DataKey> {
    const hit = this.cached(row.id);
    if (hit) return this.lend(hit);
    if (row.provider !== this.provider.kind || row.key_ref !== this.provider.keyRef) {
      throw new FieldCryptoError(`data key ${row.id} belongs to another key provider`);
    }
    const plaintext = await this.provider.unwrapDataKey(row.wrapped_key, dataKeyContext(row.field_class, row.id));
    const key: DataKey = { id: row.id, version: row.version, cls: row.field_class, key: plaintext };
    this.remember(key);
    return this.lend(key);
  }

  private async keyById(db: Queryable, id: string): Promise<DataKey> {
    const hit = this.cached(id);
    if (hit) return this.lend(hit);
    const row = (await db.query<KeyRow>(
      `SELECT id, field_class, version, provider, key_ref, wrapped_key FROM eureka.field_key WHERE id = $1`, [id])).rows[0];
    if (!row) throw new FieldCryptoError("unknown data key");
    return this.unwrap(row);
  }

  /** The newest data key of a class (a copy: release it), or null when the class has none yet. */
  async newestKey(db: Queryable, cls: FieldClass): Promise<DataKey | null> {
    const row = (await db.query<KeyRow>(
      `SELECT id, field_class, version, provider, key_ref, wrapped_key FROM eureka.field_key
        WHERE field_class = $1 ORDER BY version DESC LIMIT 1`, [cls])).rows[0];
    return row ? this.unwrap(row) : null;
  }

  /** API: the newest key (a copy), creating the class's first key when it has none (authz.field_key_first). */
  private async currentKey(db: Queryable, cls: FieldClass): Promise<DataKey> {
    const existing = await this.newestKey(db, cls);
    if (existing) return existing;
    const id = randomUUID();
    const { plaintext, wrapped } = await this.provider.generateDataKey(dataKeyContext(cls, id));
    const got = (await db.query<{ id: string; version: number }>(
      `SELECT * FROM authz.field_key_first($1, $2, $3, $4, $5)`, [id, cls, this.provider.kind, this.provider.keyRef, wrapped])).rows[0]!;
    if (got.id !== id) {
      plaintext.fill(0); // another request created the first key meanwhile
      return this.keyById(db, got.id);
    }
    const key: DataKey = { id, version: got.version, cls, key: plaintext };
    this.remember(key);
    return this.lend(key);
  }

  /**
   * Worker: the data key of the current month's rotation (authz.field_key_rotate),
   * a copy the caller releases. A retried run gets the key its first attempt
   * added. Null when the class has no key yet (nothing to rotate).
   */
  async rotationKey(db: Queryable, cls: FieldClass, runKey: string): Promise<DataKey | null> {
    const id = randomUUID();
    const { plaintext, wrapped } = await this.provider.generateDataKey(dataKeyContext(cls, id));
    let got: { id: string; version: number } | undefined;
    try {
      got = (await db.query<{ id: string; version: number }>(
        `SELECT * FROM authz.field_key_rotate($1, $2, $3, $4, $5, $6)`,
        [id, cls, this.provider.kind, this.provider.keyRef, wrapped, runKey])).rows[0];
    } catch (err) {
      plaintext.fill(0);
      throw err;
    }
    if (!got || got.id !== id) {
      plaintext.fill(0);
      return got ? this.keyById(db, got.id) : null;
    }
    const key: DataKey = { id, version: got.version, cls, key: plaintext };
    this.remember(key);
    return this.lend(key);
  }

  /** Encrypts under the class's newest key (API). Returns the ciphertext and its key id. */
  async encrypt(db: Queryable, ref: FieldRef, plaintext: string): Promise<{ enc: Buffer; keyId: string }> {
    const key = await this.currentKey(db, ref.cls);
    try {
      return { enc: sealWith(key, ref, plaintext), keyId: key.id };
    } finally {
      this.release(key);
    }
  }

  async decrypt(db: Queryable, ref: FieldRef, enc: Buffer): Promise<string> {
    const { keyId } = parseHeader(enc);
    const key = await this.keyById(db, keyId);
    try {
      return openWith(key, ref, enc);
    } finally {
      this.release(key);
    }
  }
}
